---
 - name: this play book is for arthametic operations 
   hosts: cogeco-prod
   gather_facts: false
   vars_prompt:
    - name: "x"
      prompt: enther the values of x 
      private: no
    - name: "y" 
      prompt: enther the values of y  
      private: no
   tasks:
   - debug:
       msg:
        - "The value of x is: {{x}}"
        - "The value of y is: {{x}}"
        - "{{x}} + {{y}} = {{x+y}}"
        - "{{x}} - {{y}} = {{x-y}}"
        - "{{x}} * {{y}} = {{x*y}}"
        - "{{y}} - {{x}} = {{y-x}}"
        - "x == y : {{ x == y }}"
        - "x > y : {{ x > y }}"
        - "x < y : {{ x < y }}"
        - "x != y : {{ x != y }}"

